name: Pull Request Decoration

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-decoration:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.16

      - name: Download dependencies
        run: go mod tidy

      - name: Build Go script
        run: go build -o main main.go

      - name: Run Go script
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./main
